CREATE TABLE IF NOT EXISTS weathers (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CITY VARCHAR(50) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    LAST_UPDATED TIMESTAMP NOT NULL
);