CREATE TABLE IF NOT EXISTS weathers (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CITY VARCHAR(50) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    CREATED_DATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);